### ISSUE TITLE
removing prop types causes issues

### ISSUE THREAD

**Issue by bdwain** [ReactTraining/react-media#114]
My app started having issues since #112 when I run it in prod mode. Even if the prop type verifications aren't run, some things rely on the prop types of a component to work properly (such as https://github.com/ngReact/ngReact).

Also, I have a component that wraps the Media component and reuses some of its proptypes like this

```js
MediaQueryPhoneAndTablet.propTypes = {
  children: Media.propTypes.children,
  render: Media.propTypes.render
};
```

which I think is a valid use of proptypes.

My thought is while it can save a few bytes, a library should not be removing its proptypes and if an app wants that to be done, it's up to the app to do it.

**Comment by edorivai** [comment]
Honestly curious; do you have production code that is dependent on prop types?

**Comment by bdwain** [comment]
Yea I use both of the examples I gave in my original post. While none of the actual prop type validations happen in prod, the existence of those keys is important still.

**Comment by edorivai** [comment]
Oh yeah, sorry if this was unclear, but prop types should still be available when using a development build. In 1.9.2, as long as you don't set `process.env.NODE_ENV === 'production'`, you should get a bundle including prop types. See [this piece of code](https://github.com/ReactTraining/react-media/blob/master/modules/Media.js#L76) if you're interested.

**Comment by edorivai** [comment]
Oh wait, I get what you mean now. You're not stripping _your own_ prop types, and you're referencing `Media.propTypes`, so that will break in production. I see :thinking:

**Comment by bdwain** [comment]
Yep. To me, this seems similar to minifying. It's not the job of the library author to remove the proptypes from the code. It's the job of the end user.

**Comment by edorivai** [comment]
Funny, I actually said the same [here](https://github.com/ReactTraining/react-media/issues/83#issuecomment-417254939) a while ago :sweat_smile:! However, in the thread referenced there Dan Abramov [clearly states](https://github.com/facebook/create-react-app/issues/209#issuecomment-306796251) the recommendation from the React team is to refrain from using prop types in production behavior.

He continues to say that he's comfortable with enforcing the removal of prop types in user code (in the context of CRA), but is not comfortable with removing prop types from `node_modules`, because some third party code could rely on them. I might misinterpret him here, but as I understand it he'd actually prefer it if prop types wouldn't be used in _any_ production code, including libraries.

Now I think the trade-off here is about ease of use. The current setup should work "out-of-the-box" in the majority of cases. Your suggestion of shifting the responsibility of removing prop types to the user does lend more power - you can reuse the prop types, and keep them in your production bundle if you like. However, it also makes it considerably more difficult to strip them out if you wanted to. Not only would one have to add the babel plugin, one would also have to create an exception somewhere (probably in a webpack config) to make sure `react-media` is not ignored by babel.

And as a final question to you. Besides your app referencing `Media.propTypes`, are there other ways your app breaks in production because we're stripping prop types? You mention `ngReact`, I don't know how this lib works :sweat_smile:.

**Comment by edorivai** [comment]
Interesting, so if you want to use ngReact, you wouldn't even be able to remove prop types at all.

Personally, I prefer the current setup. If we manage to find workarounds for problems like this ngReact thing, I would argue we leave it as it's currently implemented. I realize this makes it impossible in your case to reference `Media.propTypes`, since you're not stripping your prop types in your production build. But it seems you're really only doing that in a wrapper around `<Media>`, which you wouldn't write on a day-to-day basis, right?

**Comment by bdwain** [comment]
I’m not sure what you mean. I’m not writing new wrappers around the Media
component regularly. But I did want my components to be able to just pass
through certain props to Media and not have to worry about what types it
expects.

If we can find a workaround that would be great. Then it’d be the best of
both worlds. I think it would need to be generic though, since I doubt
ngreact is the only library that uses proptypes in prod

**Comment by edorivai** [comment]
I'll close this for now. In the end it's a trade off, and I'd be happy to receive feedback from people having a problem with this. If sufficiently many people run into this, we might reconsider shipping prop types in the production bundle.
