### ISSUE TITLE
Bump 1.6.0

### ISSUE THREAD

**Issue by nezed** [ReactTraining/react-media#68]
### Changelog:
- `defaultMatches` prop (#46, #50)
- `queries` prop (#38, #39, #58)
- Migrate to `prop-types` package (#66)

**Comment by bouzlibop** [comment]
Are there any plans on when it can be released?

**Comment by bouzlibop** [comment]
^ cc @mjackson

**Comment by mjackson** [comment]
I'll probably do it this week, but it won't have the `queries` prop. That code still needs some work.

**Comment by bouzlibop** [comment]
Awesome, thanks! :)

**Comment by mjackson** [comment]
Done! Just published the new release as version 1.6.0 https://github.com/ReactTraining/react-media/releases/tag/v1.6.0

Enjoy :)

**Comment by 7rulnik** [comment]
@mjackson what work you talking about? Can you describe it in new issue?

**Comment by mjackson** [comment]
@7rulnik The code accepted both the `query` and the `queries` prop, but it wasn't clear what would happen if both props were given. The way the code was written, the `query` prop would always take precedence. Instead, I'd rather just cut a 2.0 release that accepts *only* a `queries` prop. Then, if you only have a single query, just use one.

**Comment by VinSpee** [comment]
@mjackson open to doing that soon? I'm happy to PR the change.

**Comment by mjackson** [comment]
@VinSpee Yes, I'd like to do it soon. And my apologies for removing the commits you previously made. I wanted to cut another 1.x release with the `prop-types` dep so people could get rid of the warnings, but I didn't want to release with both props because it was messy. I think it'd be easier to cut a 2.x release and just change the API in a backwards-incompat way. I'll open a new issue that describes the API I'd like to see.

**Comment by mjackson** [comment]
Let's follow up in #69
